"""remove_video_status_column

Revision ID: 55cf93dc8485
Revises: 0349af856e37
Create Date: 2026-08-02 20:12:08.540530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '55cf93dc8485'
down_revision: Union[str, Sequence[str], None] = '0349af856e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False))
    # ### end Alembic commands ###
